---
ssh_keys:
  - arch
  - baron
  - bitbucket
  - clouddev
  - codeberg
  - emerald
  - github
  - gitlab
  - google
  - home
  - pkgs
  - sculch
  - sculch_old

ssh_baron_host: !vault |
  $ANSIBLE_VAULT;1.2;AES256;p
  37663465623933356364626234376333356634313161613261646533373461313663656531396630
  3362663632393737316165643637333137663963613539370a643361363661313164363339633635
  37616566376338383364323966623866613139656535353466353431636632613337613334663732
  3961333535303962360a373637616162643239303262626366623534623132653361383235353536
  6339

ssh_baron_user: !vault |
  $ANSIBLE_VAULT;1.2;AES256;p
  37666231373031383234326338633164633530666463373563623136656534306163313139326338
  3634376162663131353763373430656234636532306261340a623761663462353930366531343366
  63613264613163333535306332316632363737626366663731386566393966616436346634613337
  6562633934626431300a336539633139666162636236636232306439316135316237386539666666
  6234

ssh_emerald_host: !vault |
  $ANSIBLE_VAULT;1.2;AES256;p
  66643333373832376366333766343335363734383964313033653634383837363366633639616163
  3562646166643665336235613534353431316162363230630a663464363230313538396336333136
  63376134396637333865303139643366373730656566336434303234663937363938336466653135
  3331646461633766320a366361363765663537343266633138303864633831386639383563333962
  30626264643738326230393133633932616133396561666231653861663566666539

ssh_emerald_user: !vault |
  $ANSIBLE_VAULT;1.2;AES256;p
  30653035386466323563383166633463346136363131386163323637616562313038383931393161
  6461656161623164333932326462393633366531323034650a353231626462626465643739323639
  61363833313466316361343730316264303237303730646533663439323733393338616364666535
  3062306431393535650a333735393433623833383830363532363832386436316539313839636435
  3235

ssh_codecommit_regions:
  - eu-central-1
  - us-east-2

ssh_codecommit_user: !vault |
  $ANSIBLE_VAULT;1.2;AES256;p
  31306365666363396162623664636266303535626430633262623466336636623732303461353839
  3266323064636163313335353238383761623962323563660a336338363038323036643362626537
  34353731363634616234313230393661316132643461313662616437343435643936656539653233
  3932353037626437640a313537323936643665643364616334653732303937323736646661343965
  35616337326537333333613061656263373166376563313438653465643739376433

ssh_mariomoney_regions:
  - eu-west-1
  - us-east-1

ssh_mariomoney_user: !vault |
  $ANSIBLE_VAULT;1.2;AES256;p
  35373835396630656437386131633536613161363132663565393230623430346364363139663661
  3466383536303834313538343532626636663564613234360a653935363434663534626561376264
  66386635366166396532303962346239326636383737616639373634376338333736316236343061
  3266623734663138320a383633393963343766356261326636363261643939376631333938663964
  31316236636166396434343331643664636566303430386133343832306437623361

ssh_work_username:
  facile: !vault |
    $ANSIBLE_VAULT;1.2;AES256;w
    65353439656130393261363565333730653266613837303138393538373137633661366265626535
    3039396565616537393834323330343239313737653261610a383965313562333638386161336139
    61643434353564636366613364393631653965633335636136633363336536623135663231623166
    3166653236323438330a613964383137663566326438303262666663313331633761633430306365
    3939
